name: example_3
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - libcxx=9.0.1
  - libffi=3.2.1
  - ncurses=6.1
  - openssl=1.1.1d
  - pip=20.0.2
  - plotly=4.5.0
  - python=3.7.6
  - readline=8.0
  - retrying=1.3.3
  - setuptools=45.2.0
  - six=1.14.0
  - sqlite=3.30.1
  - tk=8.6.10
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
      - ansiwrap==0.8.4
      - appdirs==1.4.3
      - appnope==0.1.0
      - attrs==19.3.0
      - backcall==0.1.0
      - black==19.10b0
      - bleach==3.1.0
      - cachetools==4.0.0
      - chardet==3.0.4
      - click==7.0
      - colorama==0.4.3
      - cursor==1.3.4
      - decorator==4.4.1
      - defusedxml==0.6.0
      - docker==4.2.0
      - entrypoints==0.3
      - escapism==1.0.0
      - google-api-core==1.16.0
      - google-auth==1.11.0
      - google-cloud-core==1.3.0
      - google-cloud-storage==1.26.0
      - google-resumable-media==0.5.0
      - googleapis-common-protos==1.51.0
      - halo==0.0.28
      - humanfriendly==6.1
      - idna==2.8
      - importlib-metadata==1.5.0
      - ipykernel==5.1.4
      - ipython==7.12.0
      - ipython-genutils==0.2.0
      - ipywidgets==7.5.1
      - jedi==0.16.0
      - jinja2==2.11.1
      - jsonschema==3.2.0
      - jupyter==1.0.0
      - jupyter-client==5.3.4
      - jupyter-console==6.1.0
      - jupyter-core==4.6.2
      - jupyter-repo2docker==0.11.0
      - log-symbols==0.0.14
      - markupsafe==1.1.1
      - mistune==0.8.4
      - nbclient==0.1.0
      - nbconvert==5.6.1
      - nbformat==5.0.4
      - notebook==6.0.3
      - pandocfilters==1.4.2
      - papermill==2.0.0
      - parso==0.6.1
      - pathlib==1.0.1
      - pathspec==0.7.0
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - prometheus-client==0.7.1
      - prompt-toolkit==3.0.3
      - protobuf==3.11.3
      - ptyprocess==0.6.0
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pygments==2.5.2
      - pyrsistent==0.15.7
      - python-dateutil==2.8.1
      - python-json-logger==0.1.11
      - pytz==2019.3
      - pyyaml==5.3
      - pyzmq==18.1.1
      - qtconsole==4.6.0
      - regex==2020.1.8
      - requests==2.22.0
      - rsa==4.0
      - ruamel-yaml==0.16.10
      - ruamel-yaml-clib==0.2.0
      - semver==2.9.0
      - send2trash==1.5.0
      - spinners==0.0.23
      - tenacity==6.0.0
      - termcolor==1.1.0
      - terminado==0.8.3
      - testpath==0.4.4
      - textwrap3==0.9.2
      - timeago==1.0.13
      - toml==0.10.0
      - tornado==6.0.3
      - tqdm==4.42.1
      - traitlets==4.3.3
      - treebeard==0.0.63
      - typed-ast==1.4.1
      - urllib3==1.25.8
      - wcwidth==0.1.8
      - webencodings==0.5.1
      - websocket-client==0.57.0
      - widgetsnbextension==3.5.1
      - zipp==2.2.0
prefix: /usr/local/anaconda3/envs/example_3
